### PR TITLE
Fix some broken pixels on some stone tools (and the bread item texture).

### PR DESCRIPTION
**Pull request by kingoscargames**
https://github.com/SummerFields/SummerFields/issues/348

### CODE REVIEW

**Comment by CuddleWoozle** [comment]
Are you talking about the three pixel 'crumbs' on the bread or something else?

**Comment by lipki** [comment]
No, he's talking about semi-transparent pixels.
Which sometimes appears opaque, and sometimes does not appear at all.

Can you convert these three images into indexed color please.

Then I merge.

**Comment by kingoscargames** [comment]
> Can you convert these for images into indexed color please.

What do you mean?

**Comment by lipki** [comment]
https://en.wikipedia.org/wiki/Indexed_color
No problem, I'll do it later.

Thank you very much for your participation.

**Comment by tobyplowy** [comment]
@kingoscargames if you use gimp do this
naamloos

**Comment by tobyplowy** [comment]
@kingoscargames 
naamloos

than type a number in the red sircle this number represents the nember of colors but in this case you dount need to ajust that value

just clikc omzetten and your done :D

**Pull request merged**
