### PR TITLE
Colored GUI versions for each shulkers box (Optifine required) 

### PR DESCRIPTION
**Pull request by ORN-Fox**
Hello guys 👋, I like to play in survival with the Sphax Pure BD then I really liked what we do with the colorful GUI of the shulkers, which when we open a red shulker, shows a red GUI, it's practical ;)

And as I know Lipki from Gunivers and I maintain a custom version of the Enigma resource pack for my Buildmyworld project (available here : https://buildmyworld.fr/resources). I made this addition to the pack. So I do it here too :D

Results in game :

When do you think?

### CODE REVIEW

**Comment by lunapanshiel** [comment]
i think the white GUI needs more contrast, it's a bit too bleached-looking for the wood-style GUI

**Comment by ORN-Fox** [comment]
Good remark, I will rework it tomorrow ;)

**Comment by ORN-Fox** [comment]
I reworked the white GUI and it's much better! Thanks for this feedback ;)
image

**Comment by lunapanshiel** [comment]
> 
> 
> I reworked the white GUI and it's much better (left = old, right = new) ! Thanks for this feedback ;)
> image

that's perfect, it fits in with the normal GUIs nicely

**Pull request merged**
