### PR TITLE
title

### PR DESCRIPTION
**Pull request by lipki**

### CODE REVIEW

**Comment by tobyplowy** [comment]
@lipki Merge?

**Comment by tobyplowy** [comment]
@lipki Can this PR be finished and merged?

**Comment by lipki** [comment]
yes we can :)

**Comment by tobyplowy** [comment]
So what is this PR for?
I think it's for the title images.
But it is not showing the changed files
It just sais "Binary file not shown." so that is not too useful.

**Comment by lipki** [comment]
At the top, you go to the [Files changed] tab.
These are actually binary files.
But for each file, you have a [View file] button on the right.

**Pull request merged**
