### PR TITLE
Update brick_stairs.json

### PR DESCRIPTION
**Pull request by Ultharine**
dont know if i have the right base ... 1.10? right?

### CODE REVIEW

**Comment by tobyplowy** [comment]
@lipki okay now we just wait for @lipki also tank you for helping i really appreciat it :D

**Comment by tobyplowy** [comment]
@Ultharine okay now we just wait for @lipki also tank you for helping i really appreciat it :D

**Comment by Ultharine** [comment]
i'll do the same for the stone brick stairs.
i am completely new to git.
no idea how i just did that XD

**Comment by Ultharine** [comment]
do i need another pull request? or can i add it to this?

**Comment by tobyplowy** [comment]
@Ultharine XD also I think you can keep them all in one pull request

**Comment by tobyplowy** [comment]
@Ultharine Can i ask a ofTropic question?

What Community are you from Minecraft or Minetest or both?

**Comment by tobyplowy** [comment]
@Ultharine i think you can add it to this

**Comment by Ultharine** [comment]
i'm all solo ... no community
:)
never seen minetest tho ... :O

**Comment by tobyplowy** [comment]
@Ultharine You should definitely try out minetest its a free opensource minecraft clone http://www.minetest.net the community is not that big but it keeps getting bigger (also You Can Help develop The Base game with is really cool and there's also a ton of mods here is a link To the forums https://forum.minetest.net :D

**Comment by Ultharine** [comment]
i'll try it :)
thank you

**Comment by tobyplowy** [comment]
@Ultharine also (alot of also today XD) if you want summerfields for Minetest You Can it here http://summerfields.info/?tag/minetest remember minetest is very early in development

**Comment by tobyplowy** [comment]
@Ultharine if you have tried out minetest Say what you think about it ok :D

**Comment by lipki** [comment]
Thank you for your contribution.
I can not accept this pull request because it fixes the problem only for "Bricks", not for "stones bricks".
You can modify it by adding the changes to the file
Assets / minecraft / blockstates / stone_brick_stairs.json

Or I'll do it, and I'll add your name to the commit.

**Comment by lipki** [comment]
Two pull request ... ok
Well, it's ok, thank you again.

**Pull request merged**
